#Requires -Version 5.1
<#
.SYNOPSIS
    Ver2.9-rc12 人机对话界面静态检查（源码级，只读）
.DESCRIPTION
    扫描 App/Business/Customer 等嵌入 HTML，确认 rc11/rc12 统一提示函数存在，
    并报告仍使用 alert() / window.confirm() 的位置（排除 docs 目录副本）。
#>
param(
    [string]$RepoRoot = "C:\Users\Administrator\Documents\ERP"
)

$ErrorActionPreference = "Continue"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $ScriptDir "_ver29_common.ps1")

$ts = Get-Ver29Timestamp
$fileTs = Get-Ver29FileTimestamp
$reportDir = Ensure-Ver29ReportDir -RepoRoot $RepoRoot
$reportPath = Join-Path $reportDir "ver29_ui_dialogs_check_$fileTs.md"

$htmlFiles = @(
    "App.html", "Business.html", "Customer.html", "Material.html",
    "Finance.html", "Contract.html", "OperationLog.html", "TestData.html"
)

$requiredMarkers = @(
    @{ Name = "Humanize errors"; Marker = "erpHumanizeError"; File = "App.html" }
    @{ Name = "Empty html helper"; Marker = "erpEmptyHtml"; File = "App.html" }
    @{ Name = "Table empty helper"; Marker = "erpTableEmptyHtml"; File = "App.html" }
    @{ Name = "Detail message modal"; Marker = "erpShowDetailMessage"; File = "App.html" }
    @{ Name = "Oplog 8 columns"; Marker = "oplog-table-compact"; File = "OperationLog.html" }
)

$badPatterns = @(
    @{ Pattern = "alert\("; Label = "native alert()" }
    @{ Pattern = "window\.confirm\("; Label = "native window.confirm()" }
)

Write-Host "=== Ver2.9 UI Dialogs Check (rc12) ==="
Write-Host "执行时间: $ts"

$results = @()
$allPass = $true

foreach ($m in $requiredMarkers) {
    $path = Join-Path $RepoRoot $m.File
    $found = $false
    if (Test-Path $path) {
        $text = Get-Content -Path $path -Raw -Encoding UTF8
        $found = $text -like "*$($m.Marker)*"
    }
    $status = if ($found) { "PASS" } else { "FAIL"; $allPass = $false }
    $results += [PSCustomObject]@{ Check = $m.Name; File = $m.File; Marker = $m.Marker; Status = $status }
    Write-Host "[$status] $($m.Name) ($($m.File))" -ForegroundColor $(if ($found) { "Green" } else { "Red" })
}

Write-Host ""
Write-Host "--- Forbidden pattern scan (embedded HTML sources) ---"
$alertHits = @()
foreach ($f in $htmlFiles) {
    $path = Join-Path $RepoRoot $f
    if (-not (Test-Path $path)) { continue }
    $lines = Get-Content -Path $path -Encoding UTF8
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        foreach ($bp in $badPatterns) {
            if ($line -match $bp.Pattern) {
                $alertHits += [PSCustomObject]@{
                    File = $f
                    Line = $i + 1
                    Issue = $bp.Label
                    Snippet = ($line.Trim()).Substring(0, [Math]::Min(120, ($line.Trim()).Length))
                }
            }
        }
    }
}

if ($alertHits.Count -eq 0) {
    Write-Host "[PASS] No alert() / window.confirm() in embedded HTML sources" -ForegroundColor Green
    $alertStatus = "PASS"
}
else {
    Write-Host "[WARN] Found $($alertHits.Count) native dialog usages" -ForegroundColor Yellow
    $alertHits | ForEach-Object { Write-Host "  $($_.File):$($_.Line) $($_.Issue)" }
    $alertStatus = "WARN"
}

$md = @"
# Ver2.9 UI Dialogs Check (rc12)

| Field | Value |
|-------|-------|
| Time | $ts |
| Overall markers | $(if ($allPass) { 'PASS' } else { 'FAIL' }) |
| alert/confirm scan | $alertStatus |

## Required markers

| Check | File | Marker | Status |
|-------|------|--------|--------|
"@

foreach ($r in $results) {
    $md += "| $($r.Check) | $($r.File) | $($r.Marker) | $($r.Status) |`n"
}

$md += @"

## alert / window.confirm hits

"@

if ($alertHits.Count -eq 0) {
    $md += "无`n"
}
else {
    $md += "| File | Line | Issue | Snippet |`n|------|------|-------|---------|`n"
    foreach ($h in $alertHits) {
        $sn = ($h.Snippet -replace '\|', '/')
        $md += "| $($h.File) | $($h.Line) | $($h.Issue) | $sn |`n"
    }
}

$md += @"

---
*Generated by tools/erp-agent/scripts/check_ver29_ui_dialogs.ps1*
"@

Set-Content -Path $reportPath -Value $md -Encoding UTF8
Write-Host ""
Write-Host "报告: $reportPath"

if (-not $allPass) { exit 1 }
if ($alertStatus -eq "WARN") { exit 2 }
exit 0
