#Requires -Version 5.1
<#
.SYNOPSIS
    Ver2.9 regression entry: build, git guard, API health, pages, summary report.
.DESCRIPTION
    Read-only checks. Stops if build fails. Never commit/push/tag/clear data/sync prod App.
#>
param(
    [string]$RepoRoot = "C:\Users\Administrator\Documents\ERP",
    [string]$BaseUrl = "http://127.0.0.1:8787"
)

$ErrorActionPreference = "Continue"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $ScriptDir "_ver29_common.ps1")

$ts = Get-Ver29Timestamp
$fileTs = Get-Ver29FileTimestamp
$meta = Get-Ver29GitMeta -RepoRoot $RepoRoot
$reportDir = Ensure-Ver29ReportDir -RepoRoot $RepoRoot
$summaryPath = Join-Path $reportDir "ver29_regression_summary_$fileTs.md"

Write-Host "========================================"
Write-Host "  ERP Ver2.9 Regression (rc7)"
Write-Host "  Time: $ts"
Write-Host "========================================"

$stepResults = @()
$childReports = @()
$overallOk = $true
$needsManual = $false

function Add-StepResult {
    param([string]$Step, [string]$Status, [string]$Detail, [string]$Report = "")
    $script:stepResults += [PSCustomObject]@{
        Step   = $Step
        Status = $Status
        Detail = $Detail
        Report = $Report
    }
    if ($Status -eq "FAIL") { $script:overallOk = $false }
    if ($Status -in @("FAIL", "WARN", "SKIP")) { $script:needsManual = $true }
}

function Get-ExitStatus {
    param([int]$ExitCode, [string]$PassLabel = "PASS")
    if ($ExitCode -eq 0) { return $PassLabel }
    if ($ExitCode -eq 2) {
        $script:needsManual = $true
        return "WARN"
    }
    $script:overallOk = $false
    return "FAIL"
}

# Step 1: dotnet build
Write-Host ""
Write-Host ">>> [1/4] dotnet build ERP.csproj"
$altOutputDir = Join-Path $RepoRoot "bin\rc7-regression-build-check"
$buildDetail = ""
$buildSuccess = $false
$buildNote = ""

Push-Location $RepoRoot
try {
    $buildOut = & dotnet build ERP.csproj 2>&1
    $buildExit = $LASTEXITCODE
    $buildText = ($buildOut | Out-String).Trim()
    $buildDetail = $buildText

    if ($buildExit -eq 0) {
        $buildSuccess = $true
        $buildNote = "0 errors 0 warnings (bin\Debug)"
        Write-Host "[OK] Build succeeded" -ForegroundColor Green
        Add-StepResult -Step "dotnet build" -Status "PASS" -Detail $buildNote
    }
    else {
        $locked = $buildText -match "MSB302|being used by another process|locked"
        if ($locked) {
            Write-Host "[WARN] bin\Debug may be locked by ERP.exe, trying alt output dir..." -ForegroundColor Yellow
            $altOut = & dotnet build ERP.csproj -o $altOutputDir 2>&1
            $altExit = $LASTEXITCODE
            $buildDetail = ($altOut | Out-String).Trim()
            if ($altExit -eq 0) {
                $buildSuccess = $true
                $buildNote = "Alt build OK: $altOutputDir. Close ERP.exe to rebuild bin\Debug."
                Write-Host "[OK] Alt build succeeded" -ForegroundColor Green
                Add-StepResult -Step "dotnet build" -Status "PASS" -Detail $buildNote
                $needsManual = $true
            }
            else {
                Write-Host "[FAIL] Build failed (default and alt dir)" -ForegroundColor Red
                Add-StepResult -Step "dotnet build" -Status "FAIL" -Detail "Close ERP.exe and retry."
            }
        }
        else {
            Write-Host "[FAIL] Build failed" -ForegroundColor Red
            $shortDetail = $buildText.Substring(0, [Math]::Min(500, $buildText.Length))
            Add-StepResult -Step "dotnet build" -Status "FAIL" -Detail $shortDetail
        }
    }
}
finally { Pop-Location }

if (-not $buildSuccess) {
    Write-Host ""
    Write-Host "Build failed. Skipping remaining checks." -ForegroundColor Red
    $stepRows = ($stepResults | ForEach-Object { "| $($_.Step) | $($_.Status) | $($_.Detail) |" }) -join [Environment]::NewLine
    $footer = Get-Ver29SafetyFooter
    $md = @"
# Ver2.9 Regression Summary

| Field | Value |
|-------|-------|
| Time | $ts |
| Branch | $($meta.Branch) |
| Commit | ``$($meta.Commit)`` |
| Latest | $($meta.LatestCommit) |

## Steps

| Step | Status | Detail |
|------|--------|--------|
$stepRows

## Result

**FAIL** - Build failed. Later checks not run.

$footer

---
*Generated by tools/erp-agent/scripts/run_ver29_regression.ps1*
"@
    Set-Content -Path $summaryPath -Value $md -Encoding UTF8
    Write-Host "Summary: $summaryPath"
    exit 1
}

# Step 2: git guard
Write-Host ""
Write-Host ">>> [2/4] Git Guard"
$gitScript = Join-Path $ScriptDir "check_ver29_git_guard.ps1"
& powershell -ExecutionPolicy Bypass -File $gitScript -RepoRoot $RepoRoot
$gitExit = $LASTEXITCODE
$gitStatus = Get-ExitStatus -ExitCode $gitExit
Add-StepResult -Step "Git Guard" -Status $gitStatus -Detail "exit $gitExit"

# Step 3: API health
Write-Host ""
Write-Host ">>> [3/4] API Health"
$apiScript = Join-Path $ScriptDir "check_ver29_api_health.ps1"
& powershell -ExecutionPolicy Bypass -File $apiScript -RepoRoot $RepoRoot -BaseUrl $BaseUrl
$apiExit = $LASTEXITCODE
$apiStatus = Get-ExitStatus -ExitCode $apiExit
$latestApiReport = Get-ChildItem -Path $reportDir -Filter "ver29_api_health_*.md" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
$apiReportName = if ($latestApiReport) { $latestApiReport.Name } else { "" }
if ($latestApiReport) { $childReports += $latestApiReport.FullName }
Add-StepResult -Step "API Health" -Status $apiStatus -Detail "exit $apiExit" -Report $apiReportName

# Step 4: pages check
Write-Host ""
Write-Host ">>> [4/4] Pages Check"
$pagesScript = Join-Path $ScriptDir "check_ver29_pages.ps1"
& powershell -ExecutionPolicy Bypass -File $pagesScript -RepoRoot $RepoRoot -BaseUrl $BaseUrl
$pagesExit = $LASTEXITCODE
$pagesStatus = Get-ExitStatus -ExitCode $pagesExit
$latestPagesReport = Get-ChildItem -Path $reportDir -Filter "ver29_pages_check_*.md" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
$pagesReportName = if ($latestPagesReport) { $latestPagesReport.Name } else { "" }
if ($latestPagesReport) { $childReports += $latestPagesReport.FullName }
Add-StepResult -Step "Pages Check" -Status $pagesStatus -Detail "exit $pagesExit" -Report $pagesReportName

# Summary report
if ($overallOk -and $apiExit -eq 0 -and $pagesExit -eq 0) {
    $overallLabel = "PASS"
}
elseif ($buildSuccess) {
    $overallLabel = "PARTIAL - manual review needed"
}
else {
    $overallLabel = "FAIL"
}

$stepRows = ($stepResults | ForEach-Object {
    $rpt = if ($_.Report) { $_.Report } else { "-" }
    "| $($_.Step) | $($_.Status) | $($_.Detail) | $rpt |"
}) -join [Environment]::NewLine

if ($childReports.Count -gt 0) {
    $childList = ($childReports | ForEach-Object { "- ``$_``" }) -join [Environment]::NewLine
}
else {
    $childList = "- (none)"
}

$manualReview = if ($needsManual) { "yes" } else { "no" }
$buildPass = if ($buildSuccess) { "pass" } else { "fail" }
$footer = Get-Ver29SafetyFooter

$md = @"
# Ver2.9 Regression Summary

| Field | Value |
|-------|-------|
| Time | $ts |
| Branch | $($meta.Branch) |
| Commit | ``$($meta.Commit)`` |
| Latest | $($meta.LatestCommit) |
| Build | $buildNote |

## Steps

| Step | Status | Detail | Sub-report |
|------|--------|--------|------------|
$stepRows

## Sub-reports

$childList

## Result

| Item | Value |
|------|-------|
| Overall | $overallLabel |
| Manual review | $manualReview |
| Build | $buildPass |

## Notes

- Read-only regression; no business data modified
- P0 delete protection requires browser manual check
- API 401/403 when not logged in is expected

$footer

---
*Generated by tools/erp-agent/scripts/run_ver29_regression.ps1*
"@

Set-Content -Path $summaryPath -Value $md -Encoding UTF8

Write-Host ""
Write-Host "========================================"
Write-Host "  Done: $overallLabel"
Write-Host "  Summary: $summaryPath"
Write-Host "========================================"

if (-not $overallOk) { exit 1 }
if ($needsManual) { exit 2 }
exit 0
